### ISSUE TITLE
Doesn't support "Double-Repeat"

### ISSUE THREAD

**Issue by Smiles2go** [hape42/dailygammon#124] opened 2024-06-28 10:04 UTC
Version 2.0 (674) from 22. June 2024 07:24:42

Please either warn users about Double-repeat before joining a tournament or match with it, or add support to app for Double-repeat.

Apparently I joined a double-repeat tournament "DRive To Five #14" from within this app, but wasn't warned or aware in advance that is what it was. 

When tournament actually started a few days later, and it was my move, app then complains: ![image](https://github.com/hape42/dailygammon/assets/121371957/6909a56b-9f70-4a34-85cb-651f6eaaa2eb)

I guess I must play that one out in web browser. 

I see now there was a clue in tournament name, starting with "DR", and app displays the Variant. So adding a confirmation warning "App doesn't support Double-repeat variants. If you join, play must be in web browser, not this app. (Join anyway) (exit)"
![image](https://github.com/hape42/dailygammon/assets/121371957/94b35c73-f0a5-411e-a9f2-f48a8c4b3b92)

**Comment by hape42** [comment] 2024-06-28 10:36
Good idea ! I'll try to implement it, it will come with one of the next updates.

**Comment by Smiles2go** [comment] 2024-06-29 06:01
Or add button to current warning:

(Open DG in Safari)

This would be especially nice if it could enter username password automatically and get to that game, but may be too messy if DG doesn't have convenient URL structure or REST commands.

**Comment by hape42** [comment] 2024-07-03 05:58
I have solved the problem of transferring the user ID and password to a web browser. A build #677 has already been delivered via testFlight. 
![Bildschirmfoto 2024-07-03 um 07 53 45](https://github.com/hape42/dailygammon/assets/2091581/922eda5a-2fcd-46d9-a862-41604de19c27)
![Bildschirmfoto 2024-07-03 um 07 55 19](https://github.com/hape42/dailygammon/assets/2091581/b1593995-e6d4-420e-9560-1eac19514210)

**Comment by hape42** [comment] 2024-07-03 15:12
I tested it on 5 different devices and it worked everywhere. 

It won't be easy to find out why it doesn't work for you...

![Simulator Screenshot - iPhone 15 Pro - 2024-07-03 at 17 08 36](https://github.com/hape42/dailygammon/assets/2091581/88d64663-5876-4d46-9afa-e4a07280bad6)

**Comment by Smiles2go** [comment] 2024-07-03 23:12
Even harder to find now that it is working for me also. Working in both in landscape and portrait orientation. 

I don't know what changed between not working and working. Only change I'm sure of is that I now have two DR games going when there was only one before, when not working from DG. But can't think of why that might matter. 

One not ... menu button in corner is very hard to see when in Dark Mode.

**Comment by Smiles2go** [comment] 2024-07-05 01:14
Sadly, blank white screen has returned trying to play DR. Help screen is still fine and can get from there to Top Page in browser. 

When DR play was working, there was briefly a white screen flash before (correct!) game screen comes up. 

Could issue be related to navigating to game?

**Comment by hape42** [comment] 2024-07-05 06:31
We can do that, but I haven't saved your login details. it's best to send them to me by email.

So I could check in the debugger what is causing the problem.

I have tried this several dozen times on my devices and in the simulator with different configurations. It has always worked.

**Comment by Smiles2go** [comment] 2024-07-05 11:08
Ok. Sent as in-game text and also as Support email.

**Comment by Smiles2go** [comment] 2024-07-06 05:04
Same white screen happens on iPad that I just wiped and started fresh (no backups loaded). Only for Drive to Five #18. #14 is good. 

Looks like issue is specific to game positions, though I did set text size one step larger than default.

**Comment by hape42** [comment] 2024-07-06 05:55
![Simulator Screenshot - iPhone 15 Pro - 2024-07-06 at 07 45 20](https://github.com/hape42/dailygammon/assets/2091581/c5406566-a15d-484e-a79e-aa04d798fbf4)
![Simulator Screenshot - iPhone 15 Pro - 2024-07-06 at 07 46 14](https://github.com/hape42/dailygammon/assets/2091581/a238323a-5be1-4008-9edd-553d69facb78)

unfortunately I can't find any errors in the debugger, I can't create the white screen. I've tried many times, but it always works as it should.

Of course I believe you that this happens to you. I just can't recreate it.

The version would actually be ready for delivery to the Appstore. But this seems to me to be a serious problem, I'm not sure whether I should stop the delivery until we have found the cause or whether I should deliver it anyway.

Translated with www.DeepL.com/Translator (free version)

**Comment by Smiles2go** [comment] 2024-07-06 06:20
You also tried DRive #18? 

That's where I see the problem.

**Comment by Smiles2go** [comment] 2024-07-06 06:27
Maybe not so serious as to delay App Store. Not many people play DR games, and there is workaround of using Help to reach browser and play from there. 

I think bigger issue is iPhone Display Zoom set to Larger Text - can't play landscape. But portrait mode is OK as workaround.

**Comment by hape42** [comment] 2024-07-06 06:39
You have a timePool of 200 on the match, can you wait? I'll need a few days to investigate, just because I don't find anything right away doesn't mean I'm going to give up.

**Comment by Smiles2go** [comment] 2024-07-06 06:50
Ok. Will leave DR 18 and 14 unplayed for a few more days.

**Comment by hape42** [comment] 2024-07-06 07:57
I have found the problem, an update via testFlight is already on the way

**Comment by Smiles2go** [comment] 2024-07-06 08:27
Version 2.0 (678) from 06. July 2024 09:50:13

Yes, that is better now. Thank you. 

Flashes white but can then see both games 14 and 18 in browser (after a white flash, which is fine).

**Closed** 2024-07-06 12:20 UTC
